version: "3.8"

services:
  web:
    build: .
    command: ["sh", "/entrypoint.sh"]
    volumes:
      - ./app:/app
      #- ./docker:/docker
      - ./docker/entrypoint.sh:/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
