version: "3.8"

services:
  web:
    build: .
    command: ["sh", "../docker/entrypoint.sh"]
    volumes:
      - ./app:/app
      - ./docker:/docker
      - ./connection_test.py:/connection_test.py
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
