"""Rename device type to user agent

Revision ID: 2541a624c208
Revises: 8b02fd01ea19
Create Date: 2024-05-20 20:39:24.424025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2541a624c208'
down_revision: Union[str, None] = '8b02fd01ea19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('user_agent', sa.String(), nullable=True))
    op.drop_column('user_sessions', 'device_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_sessions', 'user_agent')
    # ### end Alembic commands ###
