"""Add active field to user session

Revision ID: 8b02fd01ea19
Revises: 182fca6902d0
Create Date: 2024-05-20 13:49:05.054027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b02fd01ea19'
down_revision: Union[str, None] = '182fca6902d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'active')
    # ### end Alembic commands ###
