"""Add 'used' column to token tables

Revision ID: bb344a9bac16
Revises: e9eece89f328
Create Date: 2024-05-29 22:30:12.667982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb344a9bac16'
down_revision: Union[str, None] = 'e9eece89f328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_tokens', sa.Column('used', sa.Boolean(), nullable=True))
    op.add_column('password_reset_tokens', sa.Column('used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'used')
    op.drop_column('email_verification_tokens', 'used')
    # ### end Alembic commands ###
